baseURL = 'https://anamargaridacalheiros.com/'
languageCode = 'pt'
title = 'Ana Margarida Calheiros'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false