backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "architecture"
    label: "New Architecture Page" # Used in the UI, ie.: "New Post"
    folder: "content/architecture" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", allow_multiple: False}
